<?php

namespace App\Service;

use App\Service\DB; // si besoin futur

/**
 * Service de normalisation des fichiers GTFS.
 * - Assainit l'encodage (UTF-8)
 * - Supprime BOM
 * - Normalise fins de ligne \n
 * - Valide et ajuste les colonnes vs schéma BDD (via liste fournie)
 * - Ajoute colonnes manquantes (remplies NULL dans les données)
 * - Ignore colonnes extra (retirées du header utilisé pour import, mais conservées en log)
 * - Préfixe les colonnes identifiants (optionnel, laissé à l'import actuel)
 * - Produit un résumé structuré par fichier
 */
class GTFSCleaner
{
    /** @var array<string,array{columns: string[], auto: string[]}> */
    private array $schemas;

    /** Colonnes à ignorer si présentes dans le fichier mais auto-gérées côté DB */
    private array $autoGeneratedGlobal = ['id'];

    public function __construct()
    {
        // Définition des schémas attendus pour chaque fichier GTFS (adapter selon tables existantes).
        // IMPORTANT: provider_id est géré via SET dans LOAD DATA donc on ne l'exige pas dans le fichier.
        $this->schemas = [
            'agency' => [
                'columns' => ['agency_id','provider_id','agency_name','agency_url','agency_timezone','agency_lang','agency_phone','agency_fare_url','agency_email'],
                'auto' => ['id','provider_id']
            ],
            'routes' => [
                'columns' => ['route_id','provider_id','agency_id','route_short_name','route_long_name','route_desc','route_type','route_url','route_color','route_text_color'],
                'auto' => ['id','provider_id']
            ],
            'calendar' => [
                'columns' => ['service_id','provider_id','monday','tuesday','wednesday','thursday','friday','saturday','sunday','start_date','end_date'],
                'auto' => ['id','provider_id']
            ],
            'calendar_dates' => [
                'columns' => ['service_id','provider_id','date','exception_type'],
                'auto' => ['id','provider_id']
            ],
            'shapes' => [
                'columns' => ['shape_id','provider_id','shape_pt_lat','shape_pt_lon','shape_pt_sequence','shape_dist_traveled'],
                'auto' => ['id','provider_id']
            ],
            'trips' => [
                'columns' => ['route_id','service_id','trip_id','shape_id','provider_id','trip_headsign','trip_short_name','direction_id','block_id','wheelchair_accessible','bikes_allowed'],
                'auto' => ['id','provider_id']
            ],
            'levels' => [
                'columns' => ['level_id','provider_id','level_index','level_name'],
                'auto' => ['id','provider_id']
            ],
            'stops' => [
                'columns' => ['stop_id','provider_id','stop_code','stop_name','stop_desc','stop_lat','stop_lon','zone_id','stop_url','location_type','parent_station','stop_timezone','wheelchair_boarding','level_id','platform_code'],
                'auto' => ['id','provider_id']
            ],
            'pathways' => [
                'columns' => ['pathway_id','provider_id','from_stop_id','to_stop_id','pathway_mode','is_bidirectional','length','traversal_time','stair_count','max_slope','min_width','signposted_as','reversed_signposted_as'],
                'auto' => ['id','provider_id']
            ],
            'stop_times' => [
                'columns' => ['trip_id','arrival_time','departure_time','stop_id','stop_sequence','stop_headsign','pickup_type','drop_off_type','continuous_pickup','continuous_drop_off','shape_dist_traveled','timepoint','provider_id'],
                'auto' => ['id','provider_id']
            ],
            'stop_extensions' => [
                'columns' => ['object_id','object_code','provider_id','level_position','elevator','toilet','car','bike','scooter','bus','boat','tram','train','plane'],
                'auto' => ['id','provider_id']
            ],
            'fare_rules' => [
                'columns' => ['fare_id','route_id','origin_id','destination_id','contains_id','provider_id'],
                'auto' => ['id','provider_id']
            ],
            'fare_attributes' => [
                'columns' => ['fare_id','provider_id','price','currency_type','payment_method','transfers','agency_id','transfer_duration'],
                'auto' => ['id','provider_id']
            ],
            'frequencies' => [
                'columns' => ['trip_id','start_time','end_time','headway_secs','exact_times','provider_id'],
                'auto' => ['id','provider_id']
            ],
            'feed_info' => [
                'columns' => ['feed_publisher_name','feed_publisher_url','feed_lang','default_lang','feed_start_date','feed_end_date','feed_version','feed_contact_email','feed_contact_url','provider_id'],
                'auto' => ['id','provider_id']
            ],
            'attributions' => [
                'columns' => ['attribution_id','agency_id','route_id','trip_id','organization_name','is_producer','is_operator','is_authority','attribution_url','attribution_email','attribution_phone','provider_id'],
                'auto' => ['id','provider_id']
            ],
        ];
        $this->requiredByType = [
            'trips' => ['route_id','service_id','trip_id'],
            'stop_times' => ['trip_id','stop_id','arrival_time','departure_time','stop_sequence'],
            'stops' => ['stop_id','stop_name'],
            'routes' => ['route_id','route_type'],
            'agency' => ['agency_id','agency_name'],
        ];
        $this->allowedEnum = [
            'pickup_type' => ['0','1','2','3',''],
            'drop_off_type' => ['0','1','2','3',''],
            'continuous_pickup' => ['0','1','2',''],
            'continuous_drop_off' => ['0','1','2',''],
            'wheelchair_accessible' => ['0','1','2',''],
            'bikes_allowed' => ['0','1','2',''],
        ];
        $this->numericLike = [
            'length','traversal_time','stair_count','max_slope','min_width','shape_dist_traveled','shape_pt_lat','shape_pt_lon','shape_pt_sequence','stop_lat','stop_lon','level_position','headway_secs'];
    }

    /**
     * Normalise un fichier GTFS.
     * @param string $path chemin absolu du fichier original
     * @param string $type type (routes, stops, ...)
     * @param string $providerId identifiant provider (pour éventuel usage futur)
     * @return array{output:string,summary:array}
     */
    public function normalize(string $path, string $type, string $providerId): array
    {
        $originalExists = is_file($path);
        if (!$originalExists) {
            return [
                'output' => $path,
                'summary' => [
                    'file' => $type,
                    'expected' => $this->schemas[$type]['columns'] ?? [],
                    'file_columns' => [],
                    'auto' => $this->schemas[$type]['auto'] ?? [],
                    'missing' => [],
                    'extra' => [],
                    'kept' => 0,
                    'ignored' => 0,
                    'valid' => false,
                    'note' => 'File not found'
                ]
            ];
        }

        $fh = fopen($path, 'r');
        if (!$fh) {
            return [
                'output' => $path,
                'summary' => [
                    'file' => $type,
                    'expected' => $this->schemas[$type]['columns'] ?? [],
                    'file_columns' => [],
                    'auto' => $this->schemas[$type]['auto'] ?? [],
                    'missing' => [],
                    'extra' => [],
                    'kept' => 0,
                    'ignored' => 0,
                    'valid' => false,
                    'note' => 'Cannot open file'
                ]
            ];
        }
        // Lecture header (skip BOM si présent)
        $firstLine = fgets($fh);
        if ($firstLine === false) {
            fclose($fh);
            return [
                'output' => $path,
                'summary' => [
                    'file' => $type,
                    'expected' => $this->schemas[$type]['columns'] ?? [],
                    'file_columns' => [],
                    'auto' => $this->schemas[$type]['auto'] ?? [],
                    'missing' => $this->schemas[$type]['columns'] ?? [],
                    'extra' => [],
                    'kept' => 0,
                    'ignored' => 0,
                    'valid' => false,
                    'note' => 'Empty file'
                ]
            ];
        }
        if (substr($firstLine, 0, 3) === "\xEF\xBB\xBF") {
            $firstLine = substr($firstLine, 3);
        }
        $fileColumns = str_getcsv(trim($firstLine));
        $fileColumns = array_map(static fn($c) => trim($c), $fileColumns);

        $expected = $this->schemas[$type]['columns'] ?? $fileColumns; // fallback si non défini
        $auto = $this->schemas[$type]['auto'] ?? [];

        // Colonnes à ignorer (auto/gérées)
        $ignoreInSource = array_intersect($fileColumns, $auto);

        // Calcul des manquantes (ne pas inclure celles auto-générées comme provider_id si tu les SET ailleurs?)
        $missing = [];
        foreach ($expected as $col) {
            if (!in_array($col, $fileColumns, true) && !in_array($col, $auto, true)) {
                $missing[] = $col;
            }
        }

        // Colonnes extra (ni attendues ni auto)
        $extra = [];
        foreach ($fileColumns as $col) {
            if (!in_array($col, $expected, true) && !in_array($col, $auto, true)) {
                $extra[] = $col;
            }
        }

        // Construction du header normalisé:
        // 1. Garder l'ordre original du fichier (hors colonnes auto)
        // 2. Ajouter à la fin les colonnes attendues manquantes (hors auto)
        $normalizedHeaderCols = [];
        foreach ($fileColumns as $col) {
            if (in_array($col, $auto, true)) { continue; }
            $normalizedHeaderCols[] = $col;
        }
        $appended = [];
        foreach ($expected as $col) {
            if (in_array($col, $auto, true)) { continue; }
            if (!in_array($col, $normalizedHeaderCols, true)) {
                $normalizedHeaderCols[] = $col;
                $appended[] = $col;
            }
        }

    $kept = 0; $ignored = 0; $invalidRequired = 0; $correctedValues = 0; $normalizedLines = [];
    $debugSamples = [];
    $debugLimit = 3;
        while (($row = fgetcsv($fh)) !== false) {
            if ($row === [null] || (count($row) === 1 && trim((string)$row[0]) === '')) {
                continue; // ligne vide
            }
            // Harmoniser taille: si moins de colonnes -> compléter, si plus -> tronquer
            if (count($row) < count($fileColumns)) {
                $row = array_pad($row, count($fileColumns), '');
            } elseif (count($row) > count($fileColumns)) {
                $row = array_slice($row, 0, count($fileColumns));
            }
            $rowAssoc = [];
            foreach ($fileColumns as $idx => $col) {
                $val = $this->cleanValue($row[$idx] ?? '');
                // Normalisations spécialisées
                $original = $val;
                if ($this->isTimeField($col)) {
                    if ($val !== '' && !preg_match('/^\d{1,2}:[0-5]\d:[0-5]\d$/', $val)) {
                        $val = '';
                        $correctedValues++;
                    }
                }
                if ($this->isDateField($col)) {
                    if ($val !== '') {
                        if (preg_match('/^\d{8}$/', $val)) {
                            $val = substr($val,0,4).'-'.substr($val,4,2).'-'.substr($val,6,2);
                        } elseif (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $val)) {
                            $val = '';
                            $correctedValues++;
                        }
                    }
                }
                if (isset($this->allowedEnum[$col]) && !in_array($val, $this->allowedEnum[$col], true)) {
                    $val = '';
                    $correctedValues++;
                }
                if (in_array($col, $this->numericLike, true) && $val !== '') {
                    if (!preg_match('/^-?\d+(\.\d+)?$/', $val)) {
                        $val = '';
                        $correctedValues++;
                    }
                }
                $rowAssoc[$col] = $val;
            }
            $normalizedRow = [];
            foreach ($normalizedHeaderCols as $col) {
                $normalizedRow[] = $rowAssoc[$col] ?? '';
            }
            $allEmpty = true;
            foreach ($normalizedRow as $v) { if ($v !== '') { $allEmpty = false; break; } }
            if ($allEmpty) { $ignored++; continue; }
            // Vérification champs requis
            $requiredList = $this->requiredByType[$type] ?? [];
            $missingRequired = false;
            foreach ($requiredList as $req) {
                if (!isset($rowAssoc[$req]) || $rowAssoc[$req] === '') { $missingRequired = true; break; }
            }
            if ($missingRequired) { $invalidRequired++; continue; }
            $kept++;
            if ($kept <= $debugLimit) {
                $debugSamples[] = [
                    'raw' => $row,
                    'assoc' => $rowAssoc,
                    'normalized' => $normalizedRow
                ];
            }
            $normalizedLines[] = $this->joinCsvLine($normalizedRow);
        }
        fclose($fh);

    $normalizedHeader = $this->joinCsvLine($normalizedHeaderCols);
    $normalizedContent = $normalizedHeader . "\n" . implode("\n", $normalizedLines) . "\n";

    // Nouveau comportement: ne pas écraser l'original -> écrire clean_<basename>
    $dir = dirname($path);
    $base = basename($path); // ex stops.txt
    $outPath = $dir . '/clean_' . $base; // ex clean_stops.txt
    file_put_contents($outPath, $normalizedContent);

        $valid = $kept > 0; // base minimal

        $summary = [
            'file' => $type,
            'expected' => $expected,
            'file_columns' => $fileColumns,
            'auto' => $auto,
            'missing' => $missing,
            'extra' => $extra,
            'appended' => $appended,
            'kept' => $kept,
            'ignored' => $ignored,
            'valid' => $valid,
            'invalid_required' => $invalidRequired,
            'corrected_values' => $correctedValues,
            'output_file' => $outPath,
        ];

        // Ecriture log debug si demandé (env var ou défaut) et si échantillons
        if (!empty($debugSamples)) {
            $debugDir = sys_get_temp_dir() . '/gtfs_debug';
            if (!is_dir($debugDir)) { @mkdir($debugDir, 0777, true); }
            $logFile = $debugDir . '/' . $type . '.log';
            $fhLog = @fopen($logFile, 'w');
            if ($fhLog) {
                fwrite($fhLog, "HEADER_NORMALIZED=" . implode(',', $normalizedHeaderCols) . "\n");
                fwrite($fhLog, "APPENDED=" . implode(',', $appended) . "\n");
                foreach ($debugSamples as $i => $sample) {
                    fwrite($fhLog, "--- SAMPLE " . ($i+1) . " ---\n");
                    fwrite($fhLog, 'RAW=' . implode('|', $sample['raw']) . "\n");
                    fwrite($fhLog, 'ASSOC=' . json_encode($sample['assoc'], JSON_UNESCAPED_UNICODE) . "\n");
                    fwrite($fhLog, 'NORMALIZED=' . implode('|', $sample['normalized']) . "\n");
                }
                fclose($fhLog);
            }
            $summary['debug_log'] = $logFile;
        }

        return [
            'output' => $outPath,
            'summary' => $summary,
        ];
    }

    private function splitCsvLine(string $line): array
    {
        // Simple split qui gère guillemets basiques.
        $out = [];
        $length = strlen($line);
        $current = '';
        $inQuotes = false;
        for ($i=0; $i<$length; $i++) {
            $ch = $line[$i];
            if ($ch === '"') {
                if ($inQuotes && $i+1 < $length && $line[$i+1] === '"') { // échappement
                    $current .= '"';
                    $i++;
                } else {
                    $inQuotes = !$inQuotes;
                }
            } elseif ($ch === ',' && !$inQuotes) {
                $out[] = $current;
                $current = '';
            } else {
                $current .= $ch;
            }
        }
        $out[] = $current;
        return $out;
    }

    private function joinCsvLine(array $fields): string
    {
        $escaped = [];
        foreach ($fields as $f) {
            $f = trim($f);
            if (str_contains($f, '"') || str_contains($f, ',') || str_contains($f, '\n')) {
                $f = '"' . str_replace('"', '""', $f) . '"';
            }
            $escaped[] = $f;
        }
        return implode(',', $escaped);
    }

    private function cleanValue(string $value): string
    {
        $value = trim($value);
        // Supprime caractères de contrôle sauf tab (09)
        $value = preg_replace('/[\x00-\x08\x0B-\x1F\x7F]/u', '', $value);
        return $value;
    }

    private function isTimeField(string $col): bool
    {
        return str_contains($col, 'time') && !str_contains($col, 'datetime');
    }

    private function isDateField(string $col): bool
    {
        return str_contains($col, 'date') && !str_contains($col, 'datetime');
    }
}
