# config/packages/config.yaml

parameters:
    open_data_url: 'https://transport.data.gouv.fr/api/datasets/'
    
    geosearch_url: 'https://geo.hackernwar.com/v1/'

    prim_url: 'https://prim.iledefrance-mobilites.fr/marketplace/v2/navitia'
    prim_url_trafic: 'https://prim.iledefrance-mobilites.fr/marketplace/v2/navitia/line_reports'
    prim_url_timetables: 'https://data.iledefrance-mobilites.fr/explore/dataset/fiches-horaires-et-plans/download/'
    prim_url_maps: 'https://data.iledefrance-mobilites.fr/explore/dataset/plans-region/download/'
    prim_api_key: 'prim_api_key'
    
    sncf_gc_key: 'sncf_gc_key'
    sncf_api_key: 'sncf_api_key'

    lines.hidden:
        - 'SNCF'
        - 'FUN'
        - 'TER'

    lines:
        - 'IDFM:C01742'
        - 'IDFM:C01743'
        - 'IDFM:C01727'
        - 'IDFM:C01728'
        - 'IDFM:C01729'
        - 'IDFM:C01371'
        - 'IDFM:C01372'
        - 'IDFM:C01373'
        - 'IDFM:C01386'
        - 'IDFM:C01374'
        - 'IDFM:C01375'
        - 'IDFM:C01376'
        - 'IDFM:C01377'
        - 'IDFM:C01387'
        - 'IDFM:C01378'
        - 'IDFM:C01379'
        - 'IDFM:C01380'
        - 'IDFM:C01381'
        - 'IDFM:C01382'
        - 'IDFM:C01383'
        - 'IDFM:C01384'
        - 'IDFM:C01388'
        - 'IDFM:C00563'
        - 'IDFM:C01389'
        - 'IDFM:C01390'
        - 'IDFM:C01391'
        - 'IDFM:C01679'
        - 'IDFM:C01843'
        - 'IDFM:C01684'
        - 'IDFM:C01794'
        - 'IDFM:C01774'
        - 'IDFM:C01795'
        - 'IDFM:C02317'
        - 'IDFM:C01999'
        - 'IDFM:C02529'
        - 'IDFM:C02344'
        - 'IDFM:C01737'
        - 'IDFM:C01739'
        - 'IDFM:C01738'
        - 'IDFM:C01740'
        - 'IDFM:C01736'
        - 'IDFM:C01730'
        - 'IDFM:C01731'
        - 'IDFM:C01741'