TRUNCATE agency;
TRUNCATE routes;
TRUNCATE trips;
TRUNCATE calendar;
TRUNCATE calendar_dates;
TRUNCATE stop_times;
TRUNCATE stops;
TRUNCATE stop_times;
TRUNCATE transfers;
TRUNCATE pathways;

LOAD DATA INFILE '/var/www/navika/data/gtfs/agency.txt'			INTO TABLE agency FIELDS TERMINATED BY ',' ENCLOSED BY '"'LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE '/var/www/navika/data/gtfs/calendar.txt'		INTO TABLE calendar FIELDS TERMINATED BY ',' ENCLOSED BY '"'LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE '/var/www/navika/data/gtfs/calendar_dates.txt'	INTO TABLE calendar_dates FIELDS TERMINATED BY ',' ENCLOSED BY '"'LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE '/var/www/navika/data/gtfs/pathways.txt'		INTO TABLE pathways FIELDS TERMINATED BY ',' ENCLOSED BY '"'LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE '/var/www/navika/data/gtfs/routes.txt'			INTO TABLE routes FIELDS TERMINATED BY ',' ENCLOSED BY '"'LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE '/var/www/navika/data/gtfs/stop_extensions.txt'	INTO TABLE stop_extensions FIELDS TERMINATED BY ',' ENCLOSED BY '"'LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE '/var/www/navika/data/gtfs/stop_times.txt'		INTO TABLE stop_times FIELDS TERMINATED BY ',' ENCLOSED BY '"'LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE '/var/www/navika/data/gtfs/stops.txt'			INTO TABLE stops FIELDS TERMINATED BY ',' ENCLOSED BY '"'LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE '/var/www/navika/data/gtfs/transfers.txt'		INTO TABLE transfers FIELDS TERMINATED BY ',' ENCLOSED BY '"'LINES TERMINATED BY '\n'IGNORE 1 ROWS;
LOAD DATA INFILE '/var/www/navika/data/gtfs/trips.txt'			INTO TABLE trips FIELDS TERMINATED BY ',' ENCLOSED BY '"'LINES TERMINATED BY '\n'IGNORE 1 ROWS;